# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-hello-world

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10

x-telegram-proxy-all: /api/

# The `functions` block defines what code to deploy
functions:
  time:
    handler: handler.time
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: time
          method: get

  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
